name: build chat svg

on:
  workflow_dispatch:

jobs:
  build-svg:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm install

      - name: run js
        run: node build.js

      - name: svg commit
        uses: EndBug/add-and-commit@v4
        with:
          message: "create chat.svg"
          add: "*.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}